Id;PostHistoryTypeId;PostId;RevisionGUID;CreationDate;UserId;UserDisplayName;Comment;Text
169076207;2;49311839;0a7cf069-d636-4c6a-8467-b6967839a308;2018-03-16 01:29:18;6657487;;;"I am confused on python on its installation path and configuration. &#xD;&#xA;&#xD;&#xA;I know pip this command for installation or listing the modules. &#xD;&#xA;&#xD;&#xA;The example is like pip freeze. It will show up the list of module. &#xD;&#xA;&#xD;&#xA;Recently, I got an error when I execute pip. I had python2 and python3 on the system without any virtualenv. I use ""ls"" on /usr/bin and know these python commands.&#xD;&#xA;&#xD;&#xA;`python   python2.7         python2-config  python3.4   python3m&#xD;&#xA;python2  python2.7-config  python3         python3.4m  python-config`&#xD;&#xA;&#xD;&#xA;The error message is this when I execute pip.&#xD;&#xA;&#xD;&#xA;`Traceback (most recent call last):&#xD;&#xA;  File ""/usr/local/bin/pip3"", line 11, in <module>&#xD;&#xA;    load_entry_point('pip==9.0.1', 'console_scripts', 'pip3')()&#xD;&#xA;  File ""/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py"", line 572, in load_entry_point&#xD;&#xA;    return get_distribution(dist).load_entry_point(group, name)&#xD;&#xA;  File ""/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py"", line 2752, in load_entry_point&#xD;&#xA;    return ep.load()&#xD;&#xA;  File ""/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py"", line 2405, in load&#xD;&#xA;    return self.resolve()&#xD;&#xA;  File ""/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py"", line 2411, in resolve&#xD;&#xA;    module = __import__(self.module_name, fromlist=['__name__'], level=0)&#xD;&#xA;  File ""/usr/local/lib/python2.7/dist-packages/pip/__init__.py"", line 76, in <module>&#xD;&#xA;    from pip.commands import commands, get_summaries, get_similar_commands&#xD;&#xA;  File ""/usr/local/lib/python2.7/dist-packages/pip/commands/__init__.py"", line 6, in <module>&#xD;&#xA;    from pip.commands.bundle import BundleCommand&#xD;&#xA;  File ""/usr/local/lib/python2.7/dist-packages/pip/commands/bundle.py"", line 6, in <module>&#xD;&#xA;    from pip.commands.install import InstallCommand&#xD;&#xA;  File ""/usr/local/lib/python2.7/dist-packages/pip/commands/install.py"", line 5, in <module>&#xD;&#xA;    from pip.req import InstallRequirement, RequirementSet, parse_requirements&#xD;&#xA;  File ""/usr/local/lib/python2.7/dist-packages/pip/req/__init__.py"", line 3, in <module>&#xD;&#xA;    from .req_install import InstallRequirement&#xD;&#xA;  File ""/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py"", line 42, in <module>&#xD;&#xA;    from pip.utils.hashes import Hashes&#xD;&#xA;  File ""/usr/local/lib/python2.7/dist-packages/pip/utils/hashes.py"", line 5, in <module>&#xD;&#xA;    from pip.exceptions import HashMismatch, HashMissing, InstallationError&#xD;&#xA;ImportError: cannot import name HashMissing`&#xD;&#xA;&#xD;&#xA;How to resolve this error? Why does the system show up the error?&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;"
169076208;1;49311839;0a7cf069-d636-4c6a-8467-b6967839a308;2018-03-16 01:29:18;6657487;;;An error message when execute pip
169076209;3;49311839;0a7cf069-d636-4c6a-8467-b6967839a308;2018-03-16 01:29:18;6657487;;;<python><python-3.x><python-2.7><pip>
169078274;5;49311839;f01f5d6b-4757-4877-a833-5d4e58bf5245;2018-03-16 02:39:41;3044673;;Improved formatting;"I am confused on python on its installation path and configuration. &#xD;&#xA;&#xD;&#xA;I know pip this command for installation or listing the modules. &#xD;&#xA;&#xD;&#xA;The example is like pip freeze. It will show up the list of module. &#xD;&#xA;&#xD;&#xA;Recently, I got an error when I execute pip. I had python2 and python3 on the system without any virtualenv. I use `ls` on `/usr/bin` and know these python commands.&#xD;&#xA;&#xD;&#xA;    python   python2.7         python2-config  python3.4   python3m&#xD;&#xA;    python2  python2.7-config  python3         python3.4m  python-config&#xD;&#xA;&#xD;&#xA;The error message is this when I execute pip.&#xD;&#xA;&#xD;&#xA;    Traceback (most recent call last):&#xD;&#xA;      File ""/usr/local/bin/pip3"", line 11, in <module>&#xD;&#xA;        load_entry_point('pip==9.0.1', 'console_scripts', 'pip3')()&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py"", line 572, in load_entry_point&#xD;&#xA;        return get_distribution(dist).load_entry_point(group, name)&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py"", line 2752, in load_entry_point&#xD;&#xA;        return ep.load()&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py"", line 2405, in load&#xD;&#xA;        return self.resolve()&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py"", line 2411, in resolve&#xD;&#xA;         module = __import__(self.module_name, fromlist=['__name__'], level=0)&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/__init__.py"", line 76, in <module>&#xD;&#xA;        from pip.commands import commands, get_summaries, get_similar_commands&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/commands/__init__.py"", line 6, in <module>&#xD;&#xA;        from pip.commands.bundle import BundleCommand&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/commands/bundle.py"", line 6, in <module>&#xD;&#xA;        from pip.commands.install import InstallCommand&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/commands/install.py"", line 5, in <module>&#xD;&#xA;        from pip.req import InstallRequirement, RequirementSet, parse_requirements&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/req/__init__.py"", line 3, in <module>&#xD;&#xA;        from .req_install import InstallRequirement&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py"", line 42, in <module>&#xD;&#xA;        from pip.utils.hashes import Hashes&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/utils/hashes.py"", line 5, in <module>&#xD;&#xA;        from pip.exceptions import HashMismatch, HashMissing, InstallationError&#xD;&#xA;    ImportError: cannot import name HashMissing`&#xD;&#xA;&#xD;&#xA;How to resolve this error? Why does the system show up the error?&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;"
169078275;24;49311839;f01f5d6b-4757-4877-a833-5d4e58bf5245;2018-03-16 02:39:41;;;Proposed by 3044673 approved by 149008, 6657487 edit id of 3614098;
169078521;5;49311839;f8c6a5df-b960-4539-85fa-2960dc7e1b90;2018-03-16 02:46:32;6657487;;Add contents to explain the pip command path for more investigation references.;"I am confused on python on its installation path and configuration. &#xD;&#xA;&#xD;&#xA;I know pip this command for installation or listing the modules. &#xD;&#xA;&#xD;&#xA;The example is like `pip freeze`. It will show up the list of module. &#xD;&#xA;&#xD;&#xA;Recently, I got an error when I execute pip. I had python2 and python3 on the system without any virtualenv. I use `ls` on `/usr/bin` and know these python commands and pip commands.&#xD;&#xA;&#xD;&#xA;    python   python2.7         python2-config  python3.4   python3m&#xD;&#xA;    python2  python2.7-config  python3         python3.4m  python-config&#xD;&#xA;&#xD;&#xA;`pip pip2 pip3`&#xD;&#xA;&#xD;&#xA;In addition, I use `ls` on `/usr/local/bin` and know the pip commands.&#xD;&#xA;&#xD;&#xA;`pip  pip2  pip2.7  pip3  pip3.4  pip3.5`&#xD;&#xA;&#xD;&#xA;The error message is this when I execute pip.&#xD;&#xA;&#xD;&#xA;    Traceback (most recent call last):&#xD;&#xA;      File ""/usr/local/bin/pip3"", line 11, in <module>&#xD;&#xA;        load_entry_point('pip==9.0.1', 'console_scripts', 'pip3')()&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py"", line 572, in load_entry_point&#xD;&#xA;        return get_distribution(dist).load_entry_point(group, name)&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py"", line 2752, in load_entry_point&#xD;&#xA;        return ep.load()&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py"", line 2405, in load&#xD;&#xA;        return self.resolve()&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py"", line 2411, in resolve&#xD;&#xA;         module = __import__(self.module_name, fromlist=['__name__'], level=0)&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/__init__.py"", line 76, in <module>&#xD;&#xA;        from pip.commands import commands, get_summaries, get_similar_commands&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/commands/__init__.py"", line 6, in <module>&#xD;&#xA;        from pip.commands.bundle import BundleCommand&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/commands/bundle.py"", line 6, in <module>&#xD;&#xA;        from pip.commands.install import InstallCommand&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/commands/install.py"", line 5, in <module>&#xD;&#xA;        from pip.req import InstallRequirement, RequirementSet, parse_requirements&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/req/__init__.py"", line 3, in <module>&#xD;&#xA;        from .req_install import InstallRequirement&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py"", line 42, in <module>&#xD;&#xA;        from pip.utils.hashes import Hashes&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/utils/hashes.py"", line 5, in <module>&#xD;&#xA;        from pip.exceptions import HashMismatch, HashMissing, InstallationError&#xD;&#xA;    ImportError: cannot import name HashMissing`&#xD;&#xA;&#xD;&#xA;How to resolve this error? Why does the system show up the error?&#xD;&#xA;&#xD;&#xA;"
169079651;5;49311839;c151523d-082a-4c9b-a1b0-bd7190b8306a;2018-03-16 03:12:53;6657487;;Modify the command `ls -al` to `ls -al` with awk for much more clearly explaining the question.;"I am confused on python on its installation path and configuration. &#xD;&#xA;&#xD;&#xA;I know pip this command for installation or listing the modules. &#xD;&#xA;&#xD;&#xA;The example is like `pip freeze`. It will show up the list of module. &#xD;&#xA;&#xD;&#xA;Recently, I got an error when I execute pip. I had python2 and python3 on the system without any virtualenv. I use `ls /usr/bin/python* -al | awk {print $9 $10 $11}` to know python commands and `ls /usr/bin/pip* -al` to know the pip commands.&#xD;&#xA;&#xD;&#xA;`python->python2.7`<br>&#xD;&#xA;`python2->python2.7`<br>&#xD;&#xA;`python2.7`<br>&#xD;&#xA;`python2.7-config->arm-linux-gnueabihf-python2.7-config`<br>&#xD;&#xA;`python2-config->python2.7-config`<br>&#xD;&#xA;`python3->python3.4`<br>&#xD;&#xA;`python3.4`<br>&#xD;&#xA;`python3.4m`<br>&#xD;&#xA;`python3m->python3.4m`<br>&#xD;&#xA;`python-config->python2.7-config`<br>&#xD;&#xA;&#xD;&#xA;`pip pip2 pip3`&#xD;&#xA;&#xD;&#xA;In addition, I use `ls` on `/usr/local/bin` and know the pip commands.&#xD;&#xA;&#xD;&#xA;`pip  pip2  pip2.7  pip3  pip3.4  pip3.5`&#xD;&#xA;&#xD;&#xA;The error message is this when I execute pip.&#xD;&#xA;&#xD;&#xA;    Traceback (most recent call last):&#xD;&#xA;      File ""/usr/local/bin/pip3"", line 11, in <module>&#xD;&#xA;        load_entry_point('pip==9.0.1', 'console_scripts', 'pip3')()&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py"", line 572, in load_entry_point&#xD;&#xA;        return get_distribution(dist).load_entry_point(group, name)&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py"", line 2752, in load_entry_point&#xD;&#xA;        return ep.load()&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py"", line 2405, in load&#xD;&#xA;        return self.resolve()&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py"", line 2411, in resolve&#xD;&#xA;         module = __import__(self.module_name, fromlist=['__name__'], level=0)&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/__init__.py"", line 76, in <module>&#xD;&#xA;        from pip.commands import commands, get_summaries, get_similar_commands&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/commands/__init__.py"", line 6, in <module>&#xD;&#xA;        from pip.commands.bundle import BundleCommand&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/commands/bundle.py"", line 6, in <module>&#xD;&#xA;        from pip.commands.install import InstallCommand&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/commands/install.py"", line 5, in <module>&#xD;&#xA;        from pip.req import InstallRequirement, RequirementSet, parse_requirements&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/req/__init__.py"", line 3, in <module>&#xD;&#xA;        from .req_install import InstallRequirement&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py"", line 42, in <module>&#xD;&#xA;        from pip.utils.hashes import Hashes&#xD;&#xA;      File ""/usr/local/lib/python2.7/dist-packages/pip/utils/hashes.py"", line 5, in <module>&#xD;&#xA;        from pip.exceptions import HashMismatch, HashMissing, InstallationError&#xD;&#xA;    ImportError: cannot import name HashMissing`&#xD;&#xA;&#xD;&#xA;How to resolve this error? Why does the system show up the error?"
